name: CI dbt-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install dbt-core dbt-snowflake
      - run: dbt deps
        working-directory: ./dags/data_pipeline

      - run: dbt build --select staging
        working-directory: ./dags/data_pipeline
